// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TunaPiano;

#nullable disable

namespace TunaPiano.Migrations
{
    [DbContext(typeof(TunaPianaDBContext))]
    [Migration("20240907170433_AddedSongGenreToSongModel")]
    partial class AddedSongGenreToSongModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TunaPiano.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 32,
                            Bio = "Alice Suki Waterhouse is an English singer-songwriter, actress and model. The indie pop artist released her debut studio album I Can't Let Go and debut extended play Milk Teeth in 2022.",
                            Name = "Suki Waterhouse"
                        },
                        new
                        {
                            Id = 2,
                            Age = 26,
                            Bio = "Kayleigh Rose Amstutz, known professionally as Chappell Roan, is an American singer and songwriter. Working with collaborator Dan Nigro, the majority of her music is inspired by 1980s synth-pop and early 2000s pop hits.",
                            Name = "Chappell Roan"
                        },
                        new
                        {
                            Id = 3,
                            Age = 29,
                            Bio = "Ashley Nicolette Frangipane, known professionally as Halsey, is an American singer, songwriter, and actress.",
                            Name = "Halsey"
                        },
                        new
                        {
                            Id = 4,
                            Age = 18,
                            Bio = "Cage the Elephant is an American rock band from Bowling Green, Kentucky, that formed in mid-2006. Since their formation, the band has gained a massive following in the US as well as the UK and Canada for their sound and their high-energy live performances.",
                            Name = "Cage the Elephant"
                        },
                        new
                        {
                            Id = 5,
                            Age = 14,
                            Bio = "How old are Glass Animals?\r\nGlass Animals - Wikipedia\r\nGlass Animals are an English indie rock band formed in Oxford in 2010. The band's line-up consists of Dave Bayley (vocals, guitar, keyboards, drums, songwriting), Drew MacFarlane (guitar, keyboards, backing vocals), Edmund Irwin-Singer (bass, keyboards, backing vocals), and Joe Seaward (drums).",
                            Name = "Glass Animals"
                        });
                });

            modelBuilder.Entity("TunaPiano.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Description = "Rock"
                        },
                        new
                        {
                            Id = 101,
                            Description = "Indie Pop"
                        },
                        new
                        {
                            Id = 102,
                            Description = "Alternative/Indie"
                        },
                        new
                        {
                            Id = 103,
                            Description = "Pop"
                        });
                });

            modelBuilder.Entity("TunaPiano.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<int?>("GenreId")
                        .HasColumnType("integer");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GenreId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 200,
                            Album = "The Rise and Fall of a Midwest Princess",
                            ArtistId = 2,
                            Length = 192,
                            Title = "Red Wine Supernova"
                        },
                        new
                        {
                            Id = 201,
                            Album = "The Rise and Fall of a Midwest Princess",
                            ArtistId = 2,
                            Length = 183,
                            Title = "Super Graphic Ultra Modern Girl"
                        },
                        new
                        {
                            Id = 202,
                            Album = "Badlands",
                            ArtistId = 3,
                            Length = 214,
                            Title = "Control"
                        },
                        new
                        {
                            Id = 203,
                            Album = "hopeless fountain kingdom",
                            ArtistId = 3,
                            Length = 181,
                            Title = "Bad At Love"
                        },
                        new
                        {
                            Id = 204,
                            Album = "I Can't Let Go",
                            ArtistId = 1,
                            Length = 193,
                            Title = "Moves"
                        },
                        new
                        {
                            Id = 205,
                            Album = "Blackout Drunk",
                            ArtistId = 1,
                            Length = 162,
                            Title = "My Fun"
                        },
                        new
                        {
                            Id = 206,
                            Album = "I Love You So F***ing Much",
                            ArtistId = 5,
                            Length = 224,
                            Title = "whatthehellishappening?"
                        },
                        new
                        {
                            Id = 207,
                            Album = "Dreamland",
                            ArtistId = 5,
                            Length = 238,
                            Title = "Heat Waves"
                        },
                        new
                        {
                            Id = 208,
                            Album = "Melophobia",
                            ArtistId = 4,
                            Length = 208,
                            Title = "Cigarette Daydreams"
                        },
                        new
                        {
                            Id = 209,
                            Album = "Tell Me I'm Pretty",
                            ArtistId = 4,
                            Length = 224,
                            Title = "Sweetie Little Jean"
                        },
                        new
                        {
                            Id = 210,
                            Album = "Cage the Elephant",
                            ArtistId = 4,
                            Length = 175,
                            Title = "Ain't No Rest for the Wicked"
                        });
                });

            modelBuilder.Entity("TunaPiano.Models.SongGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<int>("SongId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("SongId");

                    b.ToTable("SongsGenres");

                    b.HasData(
                        new
                        {
                            Id = 301,
                            GenreId = 103,
                            SongId = 200
                        },
                        new
                        {
                            Id = 302,
                            GenreId = 103,
                            SongId = 201
                        },
                        new
                        {
                            Id = 303,
                            GenreId = 103,
                            SongId = 202
                        },
                        new
                        {
                            Id = 304,
                            GenreId = 101,
                            SongId = 203
                        },
                        new
                        {
                            Id = 305,
                            GenreId = 102,
                            SongId = 204
                        },
                        new
                        {
                            Id = 306,
                            GenreId = 102,
                            SongId = 205
                        },
                        new
                        {
                            Id = 307,
                            GenreId = 102,
                            SongId = 206
                        },
                        new
                        {
                            Id = 308,
                            GenreId = 102,
                            SongId = 207
                        },
                        new
                        {
                            Id = 309,
                            GenreId = 102,
                            SongId = 208
                        },
                        new
                        {
                            Id = 310,
                            GenreId = 102,
                            SongId = 209
                        },
                        new
                        {
                            Id = 311,
                            GenreId = 100,
                            SongId = 210
                        });
                });

            modelBuilder.Entity("TunaPiano.Models.Song", b =>
                {
                    b.HasOne("TunaPiano.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TunaPiano.Models.Genre", null)
                        .WithMany("Songs")
                        .HasForeignKey("GenreId");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("TunaPiano.Models.SongGenre", b =>
                {
                    b.HasOne("TunaPiano.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TunaPiano.Models.Song", "Song")
                        .WithMany("SongGenres")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("TunaPiano.Models.Genre", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("TunaPiano.Models.Song", b =>
                {
                    b.Navigation("SongGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
